# Generated by Django 5.1.5 on 2025-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userView', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
