# Generated by Django 5.1.4 on 2024-12-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0002_posts_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='text',
            new_name='content_text',
        ),
    ]
