# Generated by Django 5.1.4 on 2024-12-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiView', '0003_rename_text_posts_content_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='content_img',
            new_name='content_image',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='content_vid',
            new_name='content_video',
        ),
    ]
